### ISSUE TITLE
MO5 => Unable to load some programs from tape (.K7)

### ISSUE THREAD

**Issue by MaRvIn054** [Zlika/theodore#10]
Hello,
I found out some programs on tape (.K7) that cannot be loaded properly on MO5 flavor.
An example of this is Stanley (Loriciels). The game loads and runs fine in DCMOTO. 
I know there are some hacks in others emulators to support the software protections implemented in some games, it is very likely that Stanley is protected and loading fails on Theodore due to its protection.
I've found an interesting link that describes the way tapes were protected on MO5:
[La protection des cassettes MO5 (d'après Daniel Coulom)](http://regards.sur.sciences.free.fr/histoire/ordis/protection_cassettes/protection_des_jeux_sur_cassette.htm)
Best Regards,
MaRvIn054.

**Comment by Zlika** [comment]
Thank for the link, I will have a look at it.
Theodore implements some workarounds for floppy protections on TO8/TO9+. It can even run some games that DCMOTO and/or Teo cannot on these platforms.
The MO5 emulation, on the other hand, is quite new, so there must be room for improvements.

**Comment by Zlika** [comment]
It seems that Loriciel tapes use some undocumented/invalid 6809 opcodes, not even documented in http://dragon32.info/info/undocops.html. It's a pity that dcmoto is not open source, it would be so easy to benefit from Daniel's work... I'll try to guess what is the expected behavior by debugging these programs, but it may take some time.

**Comment by Zlika** [comment]
Stanley and other Loriciel games (pulsar, pulsar2, ...) now work ok. Tell me if you find other games not working with Theodore.
Thank you for reporting this issue.
