### ISSUE TITLE
The Autostart feature misses a settings to specify a specific action 

### ISSUE THREAD

**Issue by MaRvIn054** [Zlika/theodore#9]
Hello,
The autostart feature is very helpful to automatize start of programs. 
But it doesn't work for all software:
- On TO8, we mostly have to press B but some old ones ported from TO7 may require to press C.
- On MO5, RUN" would work for most tapes, but some require to enter LOADM"",,R
I think it's very difficult to support start of all existing software. 
The fastest and easiest way would be to add a setting at core startup to specify the action required to start the program. 
For example, something like theodore_autorun_action = "C" or theodore_autorun_action="LOADM".
Maybe as a first step this new setting could only support predefined actions, and in a later release, it could be replaced some kind of macro feature. 
What do you think?

Best Regards,
MaRvIn054.

**Comment by Zlika** [comment]
Thanks for this idea. For all flavors except MO5 it's quite easy to start the game with another Basic using the virtual keyboard. For the MO5 it's more complex, the virtual keyboard does not even have all the letters required to type RUN" or LOADM"",,R (and I don't want to add too much letters because it would make the virtual keyboard unusable).
I don't know the MO5 quite well (I had a TO8), so I don't know well all the ways to start a game on it. What I would like to have is a kind of heuristic: if my understanding if right, the way to start a game depends on the language used to code it (basic vs assembly), so maybe there is a way to automatically guess the good way to start it. If you have some info on it, do not hesitate to share :-)

**Comment by MaRvIn054** [comment]
Hi, 
thanks for the feedback. 
On MO5, one way to enhance your heuristic action for tapes would be to check the first file on them during the core initialisation (that is, before showing the first screen). 
Then depending on the filename found, you can adjust the action : 
- If filename ends with .BAS => RUN" is ok
- If filename ends with .BIN => LOADM"",,R is required. 
For TO8, I beleive it's more difficult to determine what action between B or C is suitable. So for this one, maybe the easiest way (or the 1st step) would be to add the new setting I mentioned to override the defaut B action.
Thanks again for the great work. 
Best Regards,
MaRvIn054.

**Comment by Zlika** [comment]
Thanks for the MO5 tip.
For TO8 & others, I don't think a new core setting would be more simple to use than just pressing X or select a few times to move the virtual keyboard to the 'C' letter and then press Enter.

**Comment by Zlika** [comment]
I now use a heuristic to choose between RUN" and LOADM"",,R on MO5. For other models, using the virtual keyboard to choose C instead of B seems to be the most straightforward solution.
